### ISSUE TITLE
cryptic error message - Errored » Asynchronous Error

### ISSUE THREAD

**Issue by dominictarr** [vowsjs/vows#125]
this vows error tells me nearly nothing about what sort of error it is or where it may have come from.

```
✗ Errored » Asynchronous Error
    in random apps
    in test/deploy-magicword-test.js✗ Errored » 1 honored ∙ 3 errored
```

is there anyway to enable full stack traces?

**Comment by evanp** [comment]
So, I don't think this applies for 1.x, so I'm going to close this issue.
