### ISSUE TITLE
Vows finds .js files when .coffee files of the same name are passed on the command line.

### ISSUE THREAD

**Issue by elfsternberg** [vowsjs/vows#151]
When running vows on the command line, if both "mytest.js" and "mytest.coffee" exist in the directory, this command:

```
vows mytest.coffee
```

will run 'mytest.js', even if the coffee file is more recent, relevant, and specified on the command line!  Having reviewed the code for bin/vows, I can see why this happens, but it's intertwined with how vows loads tests.

**Comment by evanp** [comment]
I just tested this with 1.x, and it doesn't seem to be a problem, so I'm going to close this.
