### ISSUE TITLE
Option to prevent sub-topic "waterfalling"

### ISSUE THREAD

**Issue by bmeck** [vowsjs/vows#17]
Right now there are quite a few tests of mine that depend upon other tests, when the parent topics fail I wish there was a means to prevent the child topics from being run (just declare them as skipped somehow) so I could see more relevant information than tests failing because an expected test before them failed.

**Comment by mmhansen** [comment]
Bailing on test failure is a good idea. It's something I will try to implement in the coming versions. Thank you for your input.
