### ISSUE TITLE
Small bugs in command line argument handler

### ISSUE THREAD

**Issue by agnat** [vowsjs/vows#196]
I spotted two bugs in the command line handler. The first one is at [line 107](https://github.com/cloudhead/vows/blob/master/bin/vows#L107). Looks like the `options.reporter` is overwritten with `true` when adding --reporter to the command line. However, it turns out that this bug is currently unreachable. That's because [line 98](https://github.com/cloudhead/vows/blob/master/bin/vows#L98) and [100](https://github.com/cloudhead/vows/blob/master/bin/vows#L100) greedily grab all options starting with r or m.

Not a big thing but should probably be fixed at some point.

**Comment by evanp** [comment]
So, vows 1.x doesn't support any of these command-line options, so I'm going to close this.
