### ISSUE TITLE
Thoughts on Error-Handling (request for comments)

### ISSUE THREAD

**Issue by adamstallard** [vowsjs/vows#264]
I wrote a wiki page that outlines the current state of error-handling in vows (discounting bugs, such as #263) and how it could be improved.

[Thoughts on Error Handling](https://github.com/adamstallard/vows/wiki/Thoughts-on-Error-Handling)

**Comment by evanp** [comment]
So, I'm not sure what's going on here, and we handle errors differently in 1.x than in 0.x, more like how @adamstallard does it. I'm going to close this and we can start a new discussion if there's a need to revisit how errors work, again.
