### ISSUE TITLE
When a topic function throws, vows are called with the exception passed as topic

### ISSUE THREAD

**Issue by n2liquid** [vowsjs/vows#280]
With this code:

```
vows.describe('Throwing topic example').addBatch({
    'in this example': {
        topic: function () {
            throw 69;
        },

        'this vow gets called with the thrown value passed as topic... wtf?': function (topic) {
            assert.equal(topic, 69);
        }
    }
}).export(module);
```

I get this output:

```
  ♢ Throwing topic example

  in this example
    ✓ this vow gets called with the thrown value passed as topic... wtf?

✓ OK » 1 honored (0.007s)
```

I would seriously expect a context setup error message and an exception dump, and obviously no vows should be called for that context.

Am I missing something? This doesn't seem to be documented anywhere and I can't see how it could've been by design... Why would it even be desirable?

**Comment by evanp** [comment]
This is how vows 1.x works, by design.
