### ISSUE TITLE
Reporters

### ISSUE THREAD

**Issue by JerrySievert** [vowsjs/vows#291]
Add reporters
- [ ] Spec
- [ ] Tap
- [ ] HTML
- [ ] JSON
- [ ] XML
- [ ] DOT

**Comment by silkentrance** [comment]
@indexzero Is this still of any concern considering that the OP did not elaborate on the issue at all and vows already has all of these reporters? And why does his sidekick always bring into play the browser issue?

**Comment by JerrySievert** [comment]
again, see labels and milestone

**Comment by silkentrance** [comment]
Ah, did not see that. Is there any documentation / architectural notes or defined goals that describe the task at hand?
