### ISSUE TITLE
Is it possible to set the reporter from an explicit call?

### ISSUE THREAD

**Issue by bapti** [vowsjs/vows#311]
I'm using APIEasy which is great.

I call `suite.run` explicitly from a gulp task.

I'd like to be able to set the reporter to xunit but I can't seem to figure out how.  Is this possible to pass through in the options.  From the source it seems like it'll only be set if called from the commandline with --xunit.

Thanks for your help
Neil

**Comment by evanp** [comment]
We don't support different reporters in 1.x, so I'm going to close this.
