### ISSUE TITLE
Add assert.isEnumerable/assert.isNotEnumerable macro

### ISSUE THREAD

**Issue by silkentrance** [vowsjs/vows#326]
Sometimes you define properties using Object.defineProperty and set the enumerable flag to false.
For this I would like to have an assertion that checks whether a specific property is enumerable.

ATM I am using a custom function that Object.keys(o) and tests whether the specified key is available but it would be nice to have it readily available in vows as well.

Here is the coffee-script version I am currently using

    assert.isEnumerable = (obj, key, message = null) ->

        if obj is undefined or obj is null

            throw new TypeError 'obj is null or undefined'

        if key is undefined or key is null or key == ''

            throw new TypeError 'key is undefined or null or the empty string'

        if not (key in Object.keys obj)

            assert.fail null, null, message || "key '#{key}' is not enumerable", "isEnumerable", assert.isEnumerable

    assert.isNotEnumerable = (obj, key, message = null) ->

        if obj is undefined or obj is null

            throw new TypeError 'obj is null or undefined'

        if key is undefined or key is null or key == ''

            throw new TypeError 'key is undefined or null or the empty string'

        if key in Object.keys obj 

            assert.fail null, null, message || "key '#{key}' is enumerable", "isNotEnumerable", assert.isNotEnumerable

TIA

**Comment by silkentrance** [comment]
Since this was already integrated I will close the issue, if you don't mind.

**Comment by indexzero** [comment]
Not a problem @silkentrance! Will respond to all your other issues / PRs soon. Very busy week for me :8ball:
