### ISSUE TITLE
Proposal: multi-page html coverage report

### ISSUE THREAD

**Issue by silkentrance** [vowsjs/vows#339]
I am currently working on a multi page html coverage report to complement the existing single page report.

The report should adhere to the existing single page report's style, yet provide the user with navigable package index pages providing an overview on the package's overall coverage such as local hits and misses and coverage as well as total hits, misses and coverage across both the local files and those of the child packages and so on.

As for my own part, I am in desperate need of such a reporting facility as none of the existing tools such as istanbul would cover my projects implemented using coffee-script, nor would they generate the required reports based on the original coffee-script.

As such, I am using coffee-coverage to instrument my sources and from that I currently generate the single page html report, as it generates the required jscoverage data.

In order for this to become real, I need to make certain, backwards compatible, changes to the coverage report api and to the vows command itself, namely adding an additional -o, --out option to where to output the generated files to, which is currently always the CWD. In addition, I would like to add the following two options to the vows command, namely --coverage-html-single, which is actually an alias for --coverage-html, and --coverage-html-multi for the new multi page coverage report.

As for the API change, all reporters will have an additional parameter: outdir. While the plain text reporter will simply ignore the extra parameter, the other reporters will write their output to the specified directory. The directory will be created when missing, or, in case of the multi page report, the report might fail with an exception on non empty directories, preventing existing files from being overwritten.

In the long run, I would like to integrate this into a grunt task that would then configure vows so that it will consider user provided templates and stylesheets and other static resources such as scripts, images and so on.

I'd like to have some input on this, especially towards user defined style sheets, templates and so on. I am currently considering to use handlebars. If you have any objections to that, feel free to propose an alternate template engine.

**Comment by mmhansen** [comment]
I think @indexzero is right that the best decision will be to let users use whatever code coverage tool they want to. This is the standard when it comes to testing and it will benefit the code base to adhere to it.
