### ISSUE TITLE
vows 0.8.1 hangs after running tests

### ISSUE THREAD

**Issue by bakkerthehacker** [vowsjs/vows#341]
See https://travis-ci.org/bakkerthehacker/bramqp/builds/42438639

Even though testing is complete, vows never exits.  I can reproduce locally and moving to v0.8.0 fixes the issue.

**Comment by Mkoopajr** [comment]
I've experienced this issue as well.

**Comment by niftylettuce** [comment]
Same here! I had to downgrade `0.7.0`  to get it working again.

**Comment by evanp** [comment]
Since vows 1.x is a breaking version change, I'm going to close this issue.
