### ISSUE TITLE
Support for arbitrary javascript dialects

### ISSUE THREAD

**Issue by silkentrance** [vowsjs/vows#342]
As of now, vows supports both standard Javascript and CoffeeScript.

How about adding support for arbitrary Javascript "dialects" and provably also other languages that can be run inside the node environment or for which at least a parser/compiler can be registered for with node's require function?

grunt are using [tkellen/node-rechoir](/tkellen/node-rechoir) for this.

I think that this would be of value for vows as well...

**Comment by evanp** [comment]
Looks like the PR got closed, so I'm just going to close this.
