### ISSUE TITLE
Coverage data is not gathered when running in isolate mode

### ISSUE THREAD

**Issue by silkentrance** [vowsjs/vows#344]
Running vows in isolate mode will lose all coverage data and the coverage document will not be written out.

A provable solution would be for the parent process asking the child processes to write out the coverage data as json to a specified file. The parent process would then gather that information and merge the data so that it can then create a coverage document from that data.

**Comment by evanp** [comment]
vows 1.x doesn't do any coverage, so I'm going to close this.
