### ISSUE TITLE
vows-test.js/CrazyEmitter tests are not implemented and will fail when implementing them

### ISSUE THREAD

**Issue by silkentrance** [vowsjs/vows#350]
While working on #349 I stumbled across some test cases not being implemented in test/vows-test.js.

These test cases deal with a synchronous emitter test that will listen on custom events of the emitter. When implementing these tests I found that they will always fail as the emitter will be passed to the vow instead of the data emitted by the event upon which that vow was listening as its topics.

It turned out that in lib/vows/addVows the last success event arguments would always be used instead of the vow.binding.context.nextTopics() when calling runTest(...).

Quite a bugger, that one.

See the follow up PR for a fix for that issue.

**Comment by silkentrance** [comment]
I have discontinued using vows in favor of mocha as I am transitioning to babel/ES. Closing this now.

**Comment by silkentrance** [comment]
Reopening since it is yet to be decided whether the PR should be integrated.

**Comment by evanp** [comment]
Since it'd be almost impossible to merge into the new codebase, I'm closing this down.
