### ISSUE TITLE
Support lcov reports

### ISSUE THREAD

**Issue by apsavin** [vowsjs/vows#352]
What about lcov coverage reports? 
It's must have for [coveralls](https://coveralls.io/).

**Comment by indexzero** [comment]
Would love it. Very high priority feature. Pull request welcome :+1:

**Comment by shinnn** [comment]
+1

**Comment by evanp** [comment]
We're not doing any coverage in vows 1.x. You can work around it by using [nyc](https://github.com/istanbuljs/nyc) for example.
