### ISSUE TITLE
All the test suites that need to pass

### ISSUE THREAD

**Issue by indexzero** [vowsjs/vows#354]
## Very important
- [ ] d3
- [ ] forever
- [ ] winston 
- [ ] nconf
- [ ] director
- [ ] cradle
## Important
- [ ] godot
- [ ] prompt
- [ ] quill-{cli,composer,tar,template}
- [ ] forever-monitor
- [ ] api-easy
- [ ] cli-easy
- [ ] errs
## Nice to have
- [ ] asana-api
- [ ] http-agent
- [ ] nssocket
- [ ] portfinder
- [ ] procfile
- [ ] revalidator
- [ ] roadmap
- [ ] system.json
- [ ] window-stream

**Comment by evanp** [comment]
I don't know if we're going to try to support all of these or not with 1.x. At least we should document what breaks.
