### ISSUE TITLE
vowsjs is incompatible with 3rd party assertion libraries (and there is no reason for that)

### ISSUE THREAD

**Issue by VanTanev** [vowsjs/vows#357]
Currently, `AssertionError`s are converted to string by a function that is added to the object's prototype: https://github.com/vowsjs/vows/blob/master/lib/assert/error.js#L88

However, there is really no reason for this not to be a separate function, so that vowsjs would be able to handle `AssertionError`s that come from anywhere. When one tries to use a 3rd party assertion library, https://github.com/vowsjs/vows/blob/e9b4d769ab6cdb3b04746783e344bf28ac42ed5d/lib/vows.js#L139 gets called, and the test case will break with `undefined is not a function` because `toStringEx` is not a member on AssertionErrors thrown from that 3rd party libraries....

Or, well.. That's what's supposed to happen but for some reason (that I really can't fathom), you've decided to call your tty formatter `"console"`. Really. You overwrote the fundamental way to write to STDOUT/STDERR in node.

Your `"console"` it will silently eat any exceptions before they reach STDERR https://github.com/vowsjs/vows/blob/master/lib/vows/console.js#L102. So the _actual_ error one gets when trying to use a 3rd party lib is: `Asynchronous Error`. I wonder, hasn't this come up in development before? The way `"console"` hides errors should've very likely been an issue at some prior point.

There are probably reasons for these decisions, and I would love to learn more about them, but if possible do consider renaming `"console"` and moving `toStringEx` off `AssertionError`.

**Comment by mmhansen** [comment]
Thank you for the input. We are considering the inclusion of 3rd part assertions, but weighting it agains the simplicity gained by including our own.
