### ISSUE TITLE
How to escape / not parse asterisk char in output?

### ISSUE THREAD

**Issue by PeterDaveHello** [vowsjs/vows#362]
Hi there, I just noticed that we'll lost the asterisk char in output, and then the context may have highlight/bold style, wonder if can prevent it been parsed? It'll be very useful, thanks!

**Comment by evanp** [comment]
I think this isn't a problem in vows 1.x, so I'm going to close it.

**Comment by PeterDaveHello** [comment]
Thanks! Would v1.x be available on npm soon? I see the latest stable is v0.8.1 there.

**Comment by strugee** [comment]
It is on npm, just under the `next` dist-tag. You can try it out with `npm install vows@1.0.0-alpha.1` or `npm install vows@next`!

**Comment by PeterDaveHello** [comment]
Yes, I noticed the alpha version and seems v0.8.1 is the latest "stable" release.
