### ISSUE TITLE
assert.equal: The red character for `expected` is missing while yellow for `actual` is showed

### ISSUE THREAD

**Issue by maple-leaf** [vowsjs/vows#368]
test case:

```
const APIEasy = require('api-easy');
const assert = require('assert');

const suite = APIEasy.describe('Get /static/component-list.json');

suite.use('localhost', 9001)
    .get('/static/component-list.json')
    .expect(200)
    .expect('should respond a json', function(err, res, body) {
        assert.equal(res.headers['content-type'], 'applicationjs');  // missing red `expected` colorized
        // assert.equal('a', 'b'); // output for this is ok
    })
    .export(module);
```

And the output of `/node_modules/vows/bin/vows test/api/components-list.spec.js`:

Here's the screenshot of `assert.euqal('a', 'b')`:

[![assert.equal](http://i.stack.imgur.com/Ron39.png)](http://i.stack.imgur.com/Ron39.png)

And the screenshot of `assert.equal(res.headers['content-type'], 'applicationjs');`:

[![assert.equal2](http://i.stack.imgur.com/5YVFV.png)](http://i.stack.imgur.com/5YVFV.png)

The yellow char is good(`/`, `on`), but red is missing, instead showing white.

**Comment by evanp** [comment]
vows 1.x doesn't do colored output, so I'm going to close this for now.
