### ISSUE TITLE
graceful-fs@2 and @3 support will be removed soon

### ISSUE THREAD

**Issue by ChALkeR** [vowsjs/vows#369]
Hi. `vows` is currently `#19` in my [list of modules](https://gist.github.com/ChALkeR/d39b49642e02277d2292d66c2ea0bced) that would likely to be broken when https://github.com/nodejs/node/pull/6413 lands (which is anticipated to happen before v7.0).

Note that `graceful-fs@1` and `graceful-fs@4` are ok and would not be broken by this, but a `require()` on `graceful-fs@2` or `graceful-fs@3` would cause an error soon.

That is, runtime warning `fs: re-evaluating native module sources is not supported.` would be turned into a throw.

If you or your deps use `graceful-fs@2` or `graceful-fs@3` in runtime — you are affected. 

Tracking: https://github.com/nodejs/node/issues/5213.

**Comment by ChALkeR** [comment]
*Update: I meant `vows`, of course =).*

**Comment by mmhansen** [comment]
Thank you chalker. We will be updating dependencies very soon.

**Comment by strugee** [comment]
@mmhansen I _think_ this should've been solved when #367 was merged. But I'm not sure.

**Comment by mmhansen** [comment]
@strugee I really need to make a program that makes a force directed graph out of github issues that reference each other. :p
