### ISSUE TITLE
Convention for naming spec files?

### ISSUE THREAD

**Issue by assaf** [vowsjs/vows#37]
vows --watch assumes a convention for naming spec files, but generally it loads all the files it finds in spec/test, not just those with test-/spec- in their name.

If it filtered and only loaded files that follow the convention (when not giving explicit file names), it would be easier to work with vows and have unrelated JavaScript files in the spec directory.

My test suite includes JS files that should not be required (I load them separately), but are part of the data used for testing.

**Comment by mmhansen** [comment]
Looks like vows is picking up all files ending in .coffee or .js in the test or spec dir.   
[line 218](https://github.com/vowsjs/vows/blob/master/bin/vows)  

I'll put command line option for test file pattern in the feature list.
Everyone else has the ability to do this, so we should as well.
