### ISSUE TITLE
Upgrage Glob version

### ISSUE THREAD

**Issue by sabrehagen** [vowsjs/vows#370]
You're currently specifying `glob ~4.3.1` in your `package.json`, but `glob` is currently at `7.0.6`. Can you update your version so we don't encounter the following npm warning with respect to the use of the old glob library?

`npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

**Comment by strugee** [comment]
See #367

**Comment by sabrehagen** [comment]
@strugee That was opened over three months ago. When will it be pulled in?

**Comment by strugee** [comment]
@sabrehagen that's my point. Your guess is as good as mine.

**Comment by sabrehagen** [comment]
@indexzero?

**Comment by jufemaiz** [comment]
Reference: https://nodesecurity.io/advisories/minimatch_regular-expression-denial-of-service

**Comment by strugee** [comment]
@sabrehagen #367 got merged. Please close.

@jufemaiz this isn't relevant anymore but just to point out, that advisory doesn't matter at all in this case. Denial of Service attacks can only happen if you take untrusted input, and if you're doing that in Vows, you're going to have a very, very, _very_ Bad Time.

**Comment by indexzero** [comment]
Thanks. Closing

**Comment by strugee** [comment]
@indexzero no problem :thumbsup:

Btw, would you mind nominating a new maintainer for Vows? Seems like you don't have time to maintain it, which is fine obviously but it's a shame it's not moving forward

**Comment by mmhansen** [comment]
Hey @strugee. I'm actually getting up to speed on the code base so that I can move this amazing library forward. It's nice to know people are still interested.

**Comment by strugee** [comment]
@mmhansen oh neat! Does that mean you're getting write access?

**Comment by mmhansen** [comment]
Already got it my friend. :) Though there is really some strange/archaic stuff going on, so it's going to take a minute for me to wrap my head around it.

**Comment by strugee** [comment]
😍
