### ISSUE TITLE
Is this repo not maintained any more?

### ISSUE THREAD

**Issue by e-cloud** [vowsjs/vows#372]
@indexzero

**Comment by strugee** [comment]
No. Look at e.g. https://github.com/vowsjs/vows/issues/370#issuecomment-245959482 and the open PR list and it'll be obvious it isn't. No need to ask @indexzero who probably won't reply anyway.

**Comment by strugee** [comment]
Actually, I stand corrected. https://github.com/vowsjs/vows/pull/367#issuecomment-266558514

**Comment by e-cloud** [comment]
see, glad it's moving on
