### ISSUE TITLE
Vows v1.0.0 - Refactoring

### ISSUE THREAD

**Issue by mmhansen** [vowsjs/vows#374]
#### Code style/structure
I think that some bits of the source should be re-written. The core functionality is great, but I think there is a reliance on too many implicit actions that make the code difficult to maintain.

ex: so much `this`!
Many uses of `this`, especially where they can mean different things need to go.
```
this.run = function (options, callback) {
            var that = this;
            this.done = function(){
                that.runWithin(options, callback);
            }
            // If there is a beforeSuite defined, the tests will run only after this.done() was called.
            if(typeof(this.beforeSuiteFunc) === 'function') {
                this.beforeSuiteFunc.call(this);
                return;
            }
            this.done();
        }
```

My purpose being the rewrite is to decrease complexity and add more documentation so that it is easier for others to contribute.

Suite.js is 480 lines long. That's just unacceptable from a comprehension perspective, so I'll be massaging the code base into a more modular and functional style.

#### Breaking changes / new direction

Right now, vows uses a lot of special syntax, (batch, suite, etc) which is helpful for describing the program, but it is not necessary or particularly helpful.

Right now a basic test looks like this.
```javasciprt
vows.describe("Vows test file with camel case").addBatch({

  "The test file": {
    topic: function () {
        return { flag: true };
    },
    "is run": function (topic) {
        assert.isTrue(topic.flag);
    }
  }
}).export(module);
```
I think it should look something like this.

```
vows('Vows test file with camel case', () => {
  return {
    "The test file": {
      topic: () => {
          return { flag: true };
      },
      "is run": (topic) => {
          assert.isTrue(topic.flag);
      }
    }
  }
})

```

One of the most powerful aspects of vows is that it takes advantage of plain js objects to describe tests. I think it is simply taking this core feature to it's final purpose by making a 'batch' return a plain js object in a function body.

This testing syntax models the simplicity of the testing library tape, but the own internal working of the way vows runs the tests will stay the same. 

#### Test Execution
> Synchronous
The base case here is that the topic needs to evaluate sync functions and regular data types.

```
   topic: () => {
       return { flag: true };
   }
```

```
  topic: 10
```

```
  topic: { flag: true }
```

> Asynchronous 
Handles promises!
```
  topic: () => {
     return new Promise((resolve) => {
       setTimeout(() => {
         resolve(42)
      }, 1000)
    })
  }
```
> Legacy  
Callbacks. 
```
  topic: () => {
     fs.readFile(path.join(__dirname, 'test-file.txt'), 'utf8', this.callback);  
    })
  }
```

> Event

#### Context
The current way to handle context.
```
"A nested context": {
        topic: emitNextTick(1),

        ".": {
            topic: function (a) { return emitNextTick(2)() },

            ".": {
                topic: function (b, a) { return emitNextTick(3)() },

                ".": {
                    topic: function (c, b, a) { return emitNextTick([4, c, b, a])() },

                    "should have access to the parent topics": function (topics) {
                        assert.equal(topics.join(), [4, 3, 2, 1].join());
                    }
                },

                "from": {
                    topic: function (c, b, a) { return emitNextTick([4, c, b, a])() },

                    "the parent topics": function(topics) {
                        assert.equal(topics.join(), [4, 3, 2, 1].join());
                    }
                }
            }
        }
    },
```

#### Test Hooks
> Needs a teardown hook
it's reasonable to use a bit of state in your tests. While state can be 'setup' in an outer context, I think keeping the teardown hook is simply a good idea for a concrete place to wipe away the test state.

#### Options

Definitely need an option for requiring babel-register like chai to enable es7 support.

```bash
    "   -r, --require     Script to be run before tests",
    "  -v, --verbose     Enable verbose output",
    "  -w, --watch       Watch mode",
    "  -s, --silent      Don't report",
    "  -i, --isolate     Run each test in its own vows process",
    "  -m  PATTERN       Only run tests matching the PATTERN string",
    "  -r  PATTERN       Only run tests matching the PATTERN regexp",
    "  --json            Use JSON reporter",
    "  --spec            Use Spec reporter",
    "  --tap             Use TAP reporter",
    "  --dot-matrix      Use Dot-Matrix reporter",
    "  --xunit           Use xUnit reporter",
    "  --no-color        Don't use terminal colors",
    "  --version         Show version",
    "  -h, --help        You're staring at it"
```

**Comment by indexzero** [comment]
@mmhansen love the enthusiasm! Having been deep in the internals of `suite.js` I feel your pain about complexity. For better or for worse that complexity is derived from having sync and async topics live side by side. e.g. reimagining the example you have as async:

``` js
const fs = require('fs');
const path = require('path');
vows('Vows test file with camel case', () => {
  return {
    "The test file": {
      topic: (done) => {
          fs.readFile(path.join(__dirname, 'test-file.txt'), 'utf8', done);  
          return { flag: true };
      },
      "is run": (topic, err, contents) => {
          assert.isTrue(topic.flag);
          assert.equal(err, null);
          assert.equal(typeof contents, 'string');
      }
    }
  }
})
```

The scenario above makes choices on questions (that you could go either way on):

- How do you differentiate sync from async? The above does it the `mocha` way by checking the `arguments.length to the `topic`. This will become more difficult with nested topics if you choose to keep those
- Do you provide `err` to test functions for async topics? The above does, but today they are assumed to be broken tests unless you set `allowErrors: true` on the suite ... _?? not sure if that exists actually ??_ 
- Do you provide the literal `topic` to the results of an async topic? The above does, but that could obviously get tricky.

**Comment by mmhansen** [comment]
@indexzero hm, that's an interesting example case. Are you saying that they would try to return both an object and an async callback?

**Comment by mmhansen** [comment]
@indexzero hm, that's an interesting example case. Are you saying that they would try to return both an object and an async callback? 

I think the best behavior in that situation would be to take whatever is returned first. So in this case, I would get the `{ flag: true }` as the topic, and ignore the done that is called from readfile.

Do you think that there is a use case for that example, or is it just what a crazy user could do?

I guess things get pretty tricky when you bring in the callback pattern. If the only way to handle asyncs was to wrap them in promises then I wouldnt have much trouble differentiating those from a primitive value.

I think we can still handle callbacks with this.callback, because topics have to be passed down to children.

```
'A banana': {
        topic: new(Banana),

        'when peeled *synchronously*': {
            topic: function (banana) {
                return banana.peelSync();
            },

....
```

So your example could be
```
vows('Vows test file with camel case', () => {
  return {
    "The test file": {
      topic: () => {
        fs.readFile(path.join(__dirname, 'test-file.txt'), 'utf8', this.callback);
      },
      "is run": (err, contents) => {
        assert.equal(err, null);
        assert.equal(typeof contents, 'string');
      }
    }
  }
})

```

To be honest, I don't like using `this` too much, but it would keep everything working the same as it is now.
