### ISSUE TITLE
Watch mode doesn't re-evaluate files?

### ISSUE THREAD

**Issue by strathmeyer** [vowsjs/vows#40]
When I use watch mode, it seems to be running my tests again when I update the file, but **not** actually reloading the file before running the test again. How is this supposed to work?

Here's how I'm able to reproduce the "bug" on OSX 10.6.5:

1) Create an empty directory, and then create a subdirectory with one file `./test/test.js` with the following code:

<pre>var vows = require('vows'),
    assert = require('assert');

// Create a Test Suite
vows.describe('test').addBatch({
    'just for kicks': {
        '1 equals 1': function () {
            assert.equal(1, 1);
        }
    }
}).export(module);</pre>

2) Start `vows -w -v`, verify the line `vows watcher watching [ 'test/test.js' ]`

3) Edit test.js to say `assert.equal(1, 2);` and save. Vows will recognize the change and display "1 Broken"

4) Edit test.js back to `assert.equal(1, 1);` and save.  Vows will recognize the change, but will still display "1 Broken"!

**Comment by evanp** [comment]
So, vows 1.x doesn't support the `-w` command-line argument, so I'm going to close this issue for now.
