### ISSUE TITLE
Broken website?

### ISSUE THREAD

**Issue by bradhowes** [vowsjs/vows#407]
I am getting an strangely-formatted version of https://vowsjs.org when views in Safari 14.0 and Chrome 86. Here's a partial capture:

![Capto_Capture 2020-10-27_23-05-49_](https://user-images.githubusercontent.com/686946/97367189-fc377f80-18a8-11eb-88b0-f2a4400885d4.png)

**Comment by strugee** [comment]
Did some investigation before seeing this issue. Closing in favor of vowsjs/vowsjs.org#4 which has more details and is in the website repo. Thank you for reporting.
