### ISSUE TITLE
options.error not honored for suite

### ISSUE THREAD

**Issue by aikar** [vowsjs/vows#50]
suite.js has this.options = {error: true} in the constructor, ignoring the value you have specified in vows.options.error.

This error feature I would almost consider broken, as not every callback takes an error as first argument...

for example http.get({/**/, this.callback);
will blow up because it only has 1 argument, the response, making you have to wrap this.callback to pass null instead...

So I did 

var vows = require('vows');
vows.options.error = false; 

but noticed it still did not work due to Suite ignoring your setting.

The options.error stuff really needs to be removed from context.js line 20~ event emitter.

Have it only apply to an ACTUAL event emitter if it triggers error, not on callbacks.

What is passed to this.callback should be exactly what is passed to your test cases.

**Comment by evanp** [comment]
vows 1.x doesn't support `vows.options`, nor does it support this argument to the suite constructor, so I'm going to close this
