### ISSUE TITLE
Failure to handle promise that is resolved before promise is returned

### ISSUE THREAD

**Issue by derrickburns** [vowsjs/vows#76]
One problem with using event emitters as promises is that there is no way to find out if an event has been emitted already or not. So, using an event emitter as a promise is problemmatic if the promise has been fulfilled prior to the return from the execution of the topic, i.e. the asynchronous code is actually executed synchronously.

**Comment by omouse** [comment]
is it possible to add an example to the docs that show how one would use Vows.js with a promise-library such as Bluebird? I've tried to use Bluebird's asCallback functionality which kinda works, but there's also the EventEmitter strategy that Vows.js provides but I'm not sure how it would fit in with promises.

Thanks for the work you've done on this library, it's been really helpful!
