### ISSUE TITLE
Watcher and workflow

### ISSUE THREAD

**Issue by cam-intel** [vowsjs/vows#89]
This is just a suggestion...  in some coding work-flows, one writes the tests first, expecting them to fail.  Then as you begin the implementation, fewer and fewer tests fail until they all pass and you're done.

The watcher only watches the spec folders right now.  This means it isn't very useful for the above scenario because it only re-runs the tests when the spec changes, not when the code changes.  

Would it be possible to add other source directories (recursively) to the watcher that trigger the tests?

Thanks

**Comment by evanp** [comment]
I think this is covered in #380, so I'm going to close it for now.
